### ISSUE TITLE
what should I do?

### ISSUE THREAD

**Issue by HyunminJo** [KH-Project-AhntwoHwangtreeJo/TastyMap#55]
what should I do?

**Comment by SungACho** [comment]
Find the issue too. 
For example, a bug

**Comment by HyunminJo** [comment]
> Find the issue too.
> For example, a bug

where is a bug? I can't find it

**Comment by SungACho** [comment]
> > 문제도 찾아보십시오. 
> > 예를 들어, 버그
> 
> 버그는 어디에 있습니까? 찾을 수 없습니다


It's time to find it, friends^^

**Comment by HyunminJo** [comment]
> > > 문제도 찾아보십시오.
> > > 예를 들어, 버그
> > 
> > 
> > 버그는 어디에 있습니까? 찾을 수 없습니다
> 
> It's time to find it, friends^^

I can't complete mouse wheel. could you help me?

**Comment by HyunminJo** [comment]
Done
