### ISSUE TITLE
 When registering a restaurant, modify the manager status of the restaurant

### ISSUE THREAD

**Issue by SungACho** [KH-Project-AhntwoHwangtreeJo/TastyMap#66]
When a user registers a restaurant, change the manager status of the restaurant to'R' as the default.
(사용자가 레스토랑 등록시, 식당의 관리자 상태는 'R'를 기본으로 변경해주세요.)

**Comment by YeJinAhn** [comment]
식당 관리자 상태'R'로 변경했으니, 이슈 닫겠습니다!
